-- 1. ENUMS E TABELAS INDEPENDENTES (PAIS)
CREATE TYPE papel_usuario AS ENUM (
  'ADMIN',
  'GERENTE_FABRIL',
  'VENDEDOR',
  'ALMOXARIFE',
  'EXPEDICAO'
);

CREATE TABLE tb_tecido (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nome varchar(255) NOT NULL
);

CREATE TABLE tb_categoria (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nome varchar(255) NOT NULL
);

CREATE TABLE tb_cor (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nome varchar(255) NOT NULL,
  hex_code varchar(20)
);

CREATE TABLE tb_tamanho (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nome varchar(50) NOT NULL,
  ordem_exibicao int
);

CREATE TABLE tb_cliente (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nome varchar(255),          -- Razão Social
  nome_fantasia varchar(255), -- Nome Fantasia
  cpf_cnpj varchar(20),
  email varchar(255),
  telefone varchar(20),
  celular varchar(20),
  cep varchar(20),
  endereco varchar(255),
  bairro varchar(100),
  municipio varchar(100),
  estado varchar(2),
  historico_compras text
);

CREATE TABLE tb_transportadora (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  razao_social varchar(255),
  nome_fantasia varchar(255),
  cnpj varchar(20) UNIQUE,
  endpoint_api varchar(255),
  prazo_medio_dias int,
  ativo boolean DEFAULT true
);

CREATE TABLE tb_servico (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nome varchar(255) NOT NULL,
  preco_padrao decimal(10,2)
);

CREATE TABLE tb_usuario (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nome_completo varchar(255),
  email varchar(255) UNIQUE NOT NULL,
  senha_hash varchar(255) NOT NULL,
  papel papel_usuario NOT NULL,
  ativo boolean DEFAULT true,
  ultimo_login timestamp,
  created_at timestamp DEFAULT now()
);

-- 2. TABELAS DE PRIMEIRO NÍVEL DE DEPENDÊNCIA

CREATE TABLE tb_vendedor (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  usuario_id bigint REFERENCES tb_usuario(id),
  cpf varchar(20) UNIQUE,
  codigo_vendedor varchar(50) UNIQUE,
  percentual_comissao decimal(5,2),
  meta_mensal decimal(10,2),
  ativo boolean DEFAULT true
);

CREATE TABLE tb_produto (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nome varchar(255) NOT NULL,
  referencia_base varchar(100),
  descricao text,
  tecido_id int REFERENCES tb_tecido(id),
  categoria_id int REFERENCES tb_categoria(id),
  preco_base decimal(10,2),
  ativo boolean DEFAULT true
);

CREATE TABLE tb_ordem_corte (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  numero_lote varchar(100) UNIQUE,
  data_emissao date,
  status varchar(50), -- EM_PRODUCAO, FINALIZADA
  observacao text
);

-- 3. TABELAS DE SEGUNDO NÍVEL (Dependem de Produto, Vendedor, etc)

CREATE TABLE tb_sku (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  produto_id bigint REFERENCES tb_produto(id),
  cor_id int REFERENCES tb_cor(id),
  tamanho_id int REFERENCES tb_tamanho(id),
  codigo_barras varchar(100) UNIQUE,
  preco_venda decimal(10,2)
);

CREATE TABLE tb_pedido (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  numero_pedido varchar(50) UNIQUE NOT NULL,
  cliente_id bigint REFERENCES tb_cliente(id),
  vendedor_id bigint REFERENCES tb_vendedor(id),
  transportadora_id int REFERENCES tb_transportadora(id),
  usuario_autorizou_desconto_id bigint REFERENCES tb_usuario(id),
  
  data_criacao timestamp DEFAULT now(),
  tipo_frete varchar(50),
  valor_frete decimal(10,2),
  subtotal decimal(10,2),
  desconto_aplicado decimal(10,2),
  observacoes_nota text,
  status varchar(50)
);

-- 4. TABELAS FINAIS (Dependem de SKU, Pedido, Ordem Corte)

CREATE TABLE tb_item_ordem_corte (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  ordem_corte_id bigint REFERENCES tb_ordem_corte(id),
  sku_id bigint REFERENCES tb_sku(id),
  qtd_planejada int NOT NULL,
  qtd_produzida int DEFAULT 0
);

CREATE TABLE tb_estoque_saldo (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  sku_id bigint REFERENCES tb_sku(id),
  qtd_fisica int DEFAULT 0,
  qtd_reservada int DEFAULT 0,
  localizacao varchar(100),
  updated_at timestamp DEFAULT now()
);

CREATE TABLE tb_item_pedido (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  pedido_id bigint REFERENCES tb_pedido(id),
  sku_id bigint REFERENCES tb_sku(id),
  quantidade int NOT NULL,
  preco_unitario decimal(10,2)
);

CREATE TABLE tb_movimentacao_estoque (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tipo varchar(50), -- ENTRADA_OC, SAIDA_VENDA
  sku_id bigint REFERENCES tb_sku(id),
  quantidade int,
  ordem_corte_id bigint REFERENCES tb_ordem_corte(id),
  pedido_id bigint REFERENCES tb_pedido(id),
  usuario_responsavel_id bigint REFERENCES tb_usuario(id),
  data_hora timestamp DEFAULT now()
);

CREATE TABLE tb_item_pedido_servico (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  item_pedido_id bigint REFERENCES tb_item_pedido(id),
  servico_id int REFERENCES tb_servico(id),
  valor_cobrado decimal(10,2),
  observacao text
);